version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: bd_sysgespecole_1uue
      POSTGRES_USER: bd_sysgespecole_1uue_user
      POSTGRES_PASSWORD: uafsp8Zbn8SjaRtuy2HwJzR8xhq113ox
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: spring_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bd_sysgespecole_1uue
      SPRING_DATASOURCE_USERNAME: bd_sysgespecole_1uue_user
      SPRING_DATASOURCE_PASSWORD: uafsp8Zbn8SjaRtuy2HwJzR8xhq113ox
    ports:
      - "8080:8080"
    command: >
      sh -c "
        until pg_isready -h db -U bd_sysgespecole_1uue; do
          echo 'Attente de PostgreSQL...';
          sleep 2;
        done &&
        java -jar app.jar
      "

volumes:
  pgdata:
